version: '3'

services:
  db:
    container_name: wordpress_maridb
    image: mariadb:latest
    volumes:
      - ./tmp/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=manager
      - MYSQL_PASSWORD=secret
  web:
    container_name: wordpress_server
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - ./tmp/www:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/enpagos
    environment:
      - WORDPRESS_DB_USER=manager
      - WORDPRESS_DB_PASSWORD=secret
      - WORDPRESS_DB_HOST=db
    ports:
      - 8080:80
